# Generated by Django 5.0.2 on 2024-03-09 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_user_bio_user_city_user_country_user_house_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('first_name', models.CharField(default='', max_length=200)),
                ('last_name', models.CharField(default='', max_length=200)),
                ('bio', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(default=' ', max_length=200)),
                ('house_address', models.CharField(default=' ', max_length=500)),
                ('city', models.CharField(default=' ', max_length=500)),
                ('country', models.CharField(blank=True, default='Mauritius', max_length=500, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
