# Generated by Django 5.0.2 on 2024-04-21 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
