# Generated by Django 5.0.2 on 2024-04-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderrequest',
            name='paymentEvidence',
            field=models.FileField(blank=True, null=True, upload_to='payment_evidence/'),
        ),
    ]
