# Generated by Django 5.0.2 on 2024-03-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('fabric', 'Fabric'), ('accessory', 'Accessory')], default='fabric', max_length=20),
        ),
    ]
